-- begin MAILCOMPONENT_MAIL_FOLDER
alter table MAILCOMPONENT_MAIL_FOLDER add constraint FK_MAILCOMPONENT_MAIL_FOLDER_MAIL_BOX foreign key (MAIL_BOX_ID) references MAILCOMPONENT_MAIL_BOX(ID)^
create index IDX_MAILCOMPONENT_MAIL_FOLDER_MAIL_BOX on MAILCOMPONENT_MAIL_FOLDER (MAIL_BOX_ID)^
-- end MAILCOMPONENT_MAIL_FOLDER
-- begin MAILCOMPONENT_MAIL_BOX
alter table MAILCOMPONENT_MAIL_BOX add constraint FK_MAILCOMPONENT_MAIL_BOX_ROOT_CERTIFICATE foreign key (ROOT_CERTIFICATE_ID) references SYS_FILE(ID)^
alter table MAILCOMPONENT_MAIL_BOX add constraint FK_MAILCOMPONENT_MAIL_BOX_CLIENT_CERTIFICATE foreign key (CLIENT_CERTIFICATE_ID) references SYS_FILE(ID)^
alter table MAILCOMPONENT_MAIL_BOX add constraint FK_MAILCOMPONENT_MAIL_BOX_AUTHENTICATION foreign key (AUTHENTICATION_ID) references MAILCOMPONENT_MAIL_SIMPLE_AUTHENTICATION(ID)^
-- end MAILCOMPONENT_MAIL_BOX
